
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/factorysh/go-longrun"

[[constraint]]
  branch = "master"
  name = "github.com/t94j0/nmap"
