
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/factorysh/go-longrun"

[[constraint]]
  branch = "master"
  name = "github.com/t94j0/nmap"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"
